<a href="https://colab.research.google.com/github/RISA-source/Concepts_Of_AI-WorkSheets/blob/main/WorkSheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [5]:
import numpy as np

empty_array_1 = np.empty((2, 2))
print("Empty array 2x2:\n", empty_array_1)

ones_array = np.ones((4, 2))
print("\nAll-one array 4x2:\n", ones_array)

filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nFilled array 3x3 with 7:\n", filled_array)

sample_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros like sample_array:\n", zeros_like_array)

ones_like_array = np.ones_like(sample_array)
print("\nOnes like sample_array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list:\n", array_from_list)

Empty array 2x2:
 [[9.75496566e-316 0.00000000e+000]
 [2.12199579e-314 5.30886346e+180]]

All-one array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like sample_array:
 [[0 0 0]
 [0 0 0]]

Ones like sample_array:
 [[1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [6]:
arr_10_49 = np.arange(10, 50)
print(arr_10_49)

matrix_0_8 = np.arange(9).reshape(3, 3)
print(matrix_0_8)

identity_3 = np.eye(3)
print(identity_3)

random_30 = np.random.random(30)
mean_val = random_30.mean()
print(mean_val)

rand_10x10 = np.random.random((10, 10))
print(rand_10x10.min(), rand_10x10.max())

zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.63740436584759
0.00798901049574241 0.9941886412862557
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [7]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print(add_xy)

sub_xy = x - y
print(sub_xy)

mul_x = x * 3
print(mul_x)

square_x = x ** 2
print(square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(dot_vw)
print(dot_xv)
print(dot_xy)

concat_xy_rows = np.concatenate((x, y), axis=0)
print(concat_xy_rows)

concat_vw_cols = np.column_stack((v, w))
print(concat_vw_cols)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except Exception as e:
    print("Error:", e)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT
.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}


In [8]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = A.dot(A_inv)
print(identity_check)


AB = A.dot(B)
BA = B.dot(A)

print("AB =\n", AB)
print("BA =\n", BA)

left_side = (A.dot(B)).T
right_side = B.T.dot(A.T)

print(left_side)
print(right_side)



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [9]:
A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]])

B_sys = np.array([-1, -3, 9])

A_inv_sys = np.linalg.inv(A_sys)
X_solution = A_inv_sys.dot(B_sys)

print("Solution:", X_solution)


Solution: [ 2.  1. -2.]


In [11]:
X_linalg = np.linalg.solve(A_sys, B_sys)
print("Solution",X_linalg)


Solution [ 2.  1. -2.]
